[package]
name = "dvm"
version = "0.1.0"
authors = ["diced <pranaco2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.6.0", features = ["full"] }
reqwest = { version = "0.11.3", features = ["json", "native-tls"], default-features = false }
termion = "1.5.6"
clap = "3.0.0-beta.2"
